name: CI-Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Setup Environment
      run: echo "Setting up environment..."
    - name: Verify Files
      shell: pwsh
      run: |
        echo "Checking project structure..."
        ls -R
